config/routes.rb
Rails.application.routes.draw do

  root 'user/homes#about'

  resources :rooms, only: [:show, :create, :index] do
    resources :messages, only: [:create]
  end
  
  
  devise_for :corporations, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  namespace :public do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'pg_search' => 'homes#pg_search', as: 'pg_search'
    get 'applicants/:id/work/' => 'applicants#work', as: 'work'
    get 'corporations/edit_job' => 'corporations#edit_job', as: 'edit_job_sheet'
    patch 'corporations/update_job' => 'corporations#update_job'
    get 'posts/applicant:id/specific_index' => 'posts#specific_index'
    get 'portfolios/applicant:id/specific_index' => 'portfolios#specific_index', as: 'specific_user'
    resource :corporations, only: [:show, :edit, :update]
    resources :applicants, only: [:index, :show] do
      resources :offers, only: [:create, :destroy]
    end
    resources :posts, only: [:index, :show]
    resources :portfolios, only: [:index, :show]
    resources :sales, except: [:show, :new, :edit]
    resources :applies, only: [:index]
    resources :corpo_notices, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :applicants, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
  }

  namespace :user do
    get 'top' => 'homes#top', as: 'top'
    get 'applicants/work' => 'applicants#work', as: 'work_history'
    get 'applicants/edit_work' => 'applicants#edit_work', as: 'edit_work_history'
    patch 'applicants/update_work' => 'applicants#update_work'
    resource :applicants, only: [:show, :edit, :update]
    resources :qualifications, except: [:show, :new, :edit]
    resources :posts, except: [:new]
    resources :portfolios
    resources :offers, only: [:index]
    resources :corporations, only: [:show] do
      resources :applies, only: [:create, :destroy]
    end
    resources :user_notices, only: [:index, :destroy]
  end
  
  
end

app/views/template/_before_header.html.erb
<header>
  <div class="backcl"></div>
  <div class="logo"></div>
  <div class="loggin">
    <%= link_to "ログイン", new_session_path(resource_name) %>
  </div>
</header>

app/views/template/_footer.html.erb
<footer>
  <p class="copy">Copyright © GrowIT/Talent All Rights Reserved.</p>
</footer>

app/views/template/_header.html.erb
<header>
  <div class="logo">
    <%= link_to user_top_path do %>
      <div class="c-logo">
      </div>
    <% end %>
  </div>
  <div class="head-item">
    <div class="notification">
      <%= link_to user_applicants_path do %>
        <div class="image-profile">
        </div>
      <% end %>
    </div>
    <div class="picture">
      <%= link_to user_user_notices_path do %>
        <div id="toggle-notice" class="image-bell">
          <% if current_applicant.unchecked_user_notices.any?%>
            <span style="color: #e59322; width: 10px; font-size: 25px;">●</span>
          <% end %>
        </div>
        <P>通知</p>
      <% end %>
    </div>
    <div class="carender">
      <%= link_to destroy_applicant_session_path, method: :delete do %>
        <div class="image-logout">
        </div>
        <p>ログアウト</p>
      <% end %>
    </div>
  </div>
</header>

app/views/template/_nav.html.erb
<nav>
  <div class="first-box">
    <div id="toggle-prof" class="widget-header">
      <h3>プロフィール</h3>
    </div>
    <div class="widget-header hide-menu">
      <h3>プロフィール</h3>
    </div>
    <ul id="menu-prof" >
      <li>
        <%= link_to 'プロフィール編集', edit_user_applicants_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to '資格情報追加', user_qualifications_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to '職務経歴確認', user_work_history_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to '職務経歴編集', user_edit_work_history_path, style: 'color: black; text-decoration: none;' %>
      </li>
    </ul>
  </div>
  <div class="second-box">
    <div id="toggle-post" class="widget-header">
      <h3>投稿</h3>
    </div>
    <div class="widget-header hide-menu">
      <h3>投稿</h3>
    </div>
    <ul id="menu-post" >
      <li>
        <%= link_to '学習記事投稿一覧', user_posts_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to 'ポートフォリオ投稿', new_user_portfolio_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to 'ポートフォリオ一覧', user_portfolios_path, style: 'color: black; text-decoration: none;' %>
      </li>
    </ul>
  </div>
  <div class="third-box">
    <div id="toggle-con" class="widget-header">
      <h3>企業とのコンタクト</h3>
    </div>
    <div class="widget-header hide-menu">
      <h3>企業とのコンタクト</h3>
    </div>
    <ul id="menu-con" >
      <li>
        <%= link_to 'オファーリスト', user_offers_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to 'メッセージリスト', rooms_path, style: 'color: black; text-decoration: none;' %>
      </li>
    </ul>
  </div>
</nav>

app/views/template/_post_head.html.erb
<div class="prof-box">
  <%= image_tag current_applicant.image_id.url, class: "item_image" %>
  <div class="creat-ttl">
    <p><%= current_applicant.full_name %> </p>
    <p><span><%= l post.created_at, format: :long %> </span></p>
  </div>
</div>

app/views/template/_public_header.html.erb
<header>
  <div class="logo">
    <%= link_to public_top_path do %>
      <div class="c-logo">
      </div>
    <% end %>
  </div>
  <div class="head-item">
    <div class="notification">
      <%= link_to public_corporations_path do %>
        <div class="image-profile">
        </div>
      <% end %>
    </div>
    <div class="picture">
      <%= link_to public_corpo_notices_path do %>
        <div class="image-bell">
          <% if current_corporation.unchecked_corpo_notices.any? %>
            <span style="color: #e59322; width: 10px; font-size: 25px;">●</span>
          <% end %>
        </div>
        <P>通知</p>
      <% end %>
    </div>
    <div class="carender">
      <%= link_to destroy_corporation_session_path, method: :delete do %>
        <div class="image-logout">
        </div>
        <p>ログアウト</p>
      <% end %>
    </div>
  </div>
</header>

app/views/template/_public_nav.html.erb
<nav>
  <div class="first-box">
    <div id="toggle-prof" class="widget-header">
      <h3>登録情報編集</h3>
    </div>
    <div class="widget-header hide-menu">
      <h3>登録情報編集</h3>
    </div>
    <ul id="menu-prof">
      <li>
        <%= link_to '企業情報編集', edit_public_corporations_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to '求人情報編集', public_edit_job_sheet_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to '売上情報追加/編集', public_sales_path, style: 'color: black; text-decoration: none;' %>
      </li>
    </ul>
  </div>
  <div class="second-box">
    <div id="toggle-post" class="widget-header">
      <h3>一覧</h3>
    </div>
    <div class="widget-header hide-menu">
      <h3>一覧</h3>
    </div>
    <ul id="menu-post">
      <li>
        <%= link_to 'ユーザー一覧', public_applicants_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to '学習記事一覧', public_posts_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to 'ポートフォリオ一覧', public_portfolios_path, style: 'color: black; text-decoration: none;' %>
      </li>
    </ul>
  </div>
  <div class="third-box">
    <div id="toggle-con" class="widget-header">
      <h3>応募者とのコンタクト</h3>
    </div>
    <div class="widget-header hide-menu">
      <h3>応募者とのコンタクト</h3>
    </div>
    <ul id="menu-con">
      <li>
        <%= link_to '応募者リスト', public_applies_path, style: 'color: black; text-decoration: none;' %>
      </li>
      <li>
        <%= link_to 'メッセージリスト', rooms_path, style: 'color: black; text-decoration: none;' %>
      </li>
    </ul>
  </div>
</nav>

app/views/template/_user_info.html.erb
<div class="basic-info">
  <%= image_tag current_applicant.image_id.url, class: "item_image" %>
  <table>
    <tr>
      <td>ふりがな</td>
      <th><%= current_applicant.full_name_kana %></th>
    </tr>
    <tr>
      <td>氏名</td>
      <th><%= current_applicant.full_name %></th>
    </tr>
    <tr>
      <td>生年月日</td>
      <th><%= l current_applicant.birth_date %>（満<%= current_applicant.age %>歳）</th>
    </tr>
    <tr>
      <td>性別</td>
      <th><%= current_applicant.gender %> </th>
    </tr>
    <tr>
      <td>郵便番号</td>
      <th><%= current_applicant.postal_code %></th>
    </tr>
    <tr>
      <td>ふりがな</td>
      <th><%= current_applicant.prefecture_kana %></th>
    </tr>
    <tr>
      <td>住所</td>
      <th><%= current_applicant.prefecture %><%= current_applicant.manicipal %><br><%= current_applicant.address_other %></th>
    </tr>
    <tr>
      <td>TEL</td>
      <th><%= current_applicant.phone_number %></th>
    </tr>
    <tr>
      <td>email</td>
      <th><%= current_applicant.email %></th>
    </tr>
  </table>
</div>