config/routes.rb
Rails.application.routes.draw do

  root 'user/homes#about'

  resources :rooms, only: [:show, :create, :index] do
    resources :messages, only: [:create]
  end
  
  
  devise_for :corporations, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  namespace :public do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'pg_search' => 'homes#pg_search', as: 'pg_search'
    get 'applicants/:id/work/' => 'applicants#work', as: 'work'
    get 'corporations/edit_job' => 'corporations#edit_job', as: 'edit_job_sheet'
    patch 'corporations/update_job' => 'corporations#update_job'
    get 'posts/applicant:id/specific_index' => 'posts#specific_index'
    get 'portfolios/applicant:id/specific_index' => 'portfolios#specific_index', as: 'specific_user'
    resource :corporations, only: [:show, :edit, :update]
    resources :applicants, only: [:index, :show] do
      resources :offers, only: [:create, :destroy]
    end
    resources :posts, only: [:index, :show]
    resources :portfolios, only: [:index, :show]
    resources :sales, except: [:show, :new, :edit]
    resources :applies, only: [:index]
    resources :corpo_notices, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :applicants, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
  }

  namespace :user do
    get 'top' => 'homes#top', as: 'top'
    get 'applicants/work' => 'applicants#work', as: 'work_history'
    get 'applicants/edit_work' => 'applicants#edit_work', as: 'edit_work_history'
    patch 'applicants/update_work' => 'applicants#update_work'
    resource :applicants, only: [:show, :edit, :update]
    resources :qualifications, except: [:show, :new, :edit]
    resources :posts, except: [:new]
    resources :portfolios
    resources :offers, only: [:index]
    resources :corporations, only: [:show] do
      resources :applies, only: [:create, :destroy]
    end
    resources :user_notices, only: [:index, :destroy]
  end
  
  
end

app/models/corporation.rb
class Corporation < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sales, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :offered_applicant, through: :offers, source: :applicant
  has_many :applies, dependent: :destroy
  has_many :applied_applicants, through: :applies, source: :applicant
  has_many :rooms, dependent: :destroy
  has_many :room_applicants, through: :rooms, source: :applicant
  has_many :user_notices, dependent: :destroy
  has_many :corpo_notices, dependent: :destroy
  has_many :tag_relations, dependent: :destroy
  has_many :tags, through: :tag_relations, dependent: :destroy

  validates :name, presence: true
  
  def already_offered?(applicant)
    self.offers.exists?(applicant_id: applicant.id)
  end

  def already_room?(applicant)
    self.rooms.exists?(applicant_id: applicant.id)
  end

  def unchecked_corpo_notices
    self.corpo_notices.where(is_check: false)
  end
end

app/controllers/user/applicants_controller.rb
class User::ApplicantsController < ApplicationController
  before_action :authenticate_applicant!

  def show
    @qualifications = current_applicant.qualifications
  end

  def edit
    @applicant = current_applicant
  end

  def update
    @applicant = current_applicant
		if @applicant.update(applicant_params)
			redirect_to user_applicants_path
		else
			render action: :edit
    end
  end

  def work
  end

  def edit_work
    @applicant = current_applicant
  end

  def update_work
    @applicant = current_applicant
		if @applicant.update(applicant_params)
			redirect_to user_work_history_path
		else
			render action: :edit_work
    end
  end

  private
  def applicant_params
    params.require(:applicant).permit(:email, :last_name, :first_name, :last_furigana, :first_furigana, :gender, :birth_date, :image_id, :postal_code,
                                      :prefecture, :manicipal, :address_other, :phone_number, :school_division, :school_name, :faculty, :academic_decipline,
                                      :english_skill, :other_lang, :overview_w_history, :is_selection, :start_work, :work_location, :axis,
                                      :company_type, :pg_skill, :self_pr, :vision, :term_1, :term_2, :term_3, :term_4, :term_5, :work_history_1,
                                      :work_history_2, :work_history_3, :work_history_4, :work_history_5, :prefecture_kana, pg_lang_ids: [])
  end
end

app/controllers/user/applies_controller.rb
class User::AppliesController < ApplicationController
  before_action :authenticate_applicant!

  def create
    @apply = current_applicant.applies.create(corporation_id: params[:corporation_id])
    @apply.create_corpo_notice_apply(@apply.corporation.id, @apply.id, @apply.applicant.id)
    redirect_to user_corporation_path(@apply.corporation_id)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/corporations_controller.rb
class User::CorporationsController < ApplicationController
  before_action :authenticate_applicant!

  def show
    @corporation = Corporation.find(params[:id])
  end

  
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  def top
    @post = Post.new
    @offers = current_applicant.offers
    @rooms = current_applicant.rooms
    @applicant = current_applicant
  end

  def about
  end
  
end

app/controllers/user/offers_controller.rb
class User::OffersController < ApplicationController
  before_action :authenticate_applicant!

  def index
    @applicant = current_applicant
  end

end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/portfolios_controller.rb
class User::PortfoliosController < ApplicationController
  before_action :authenticate_applicant!

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      redirect_to user_portfolio_path(@portfolio)
    else
      render :new
    end
  end

  def show
    @portfolio = Portfolio.find(params[:id])
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    if @portfolio.update(portfolio_params)
      redirect_to user_portfolio_path(@portfolio)
    else
      render :show
    end
  end

  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy
    redirect_to user_portfolios_path
  end

  def index
    @portfolios = current_applicant.portfolios
  end
  
  private
  def portfolio_params
    params.require(:portfolio).permit(:applicant_id, :title, :content, :theme,
                                      :reason, :target, :scene, :link_url, pg_lang_ids: [])
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_applicant!

  def index
    @posts = current_applicant.posts
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to user_post_path(@post)
    else
      render 'homes/top'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_posts_path
    else
      render :show
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path
  end
  
  
  private
  def post_params
    params.require(:post).permit(:applicant_id, :pg_lang_id, :title, :content, pg_lang_ids: [])
  end
end

app/controllers/user/qualifications_controller.rb
class User::QualificationsController < ApplicationController
  before_action :authenticate_applicant!

  def index
    @qualifications = current_applicant.qualifications
    @qualification = Qualification.new
  end
  
  def create
    @qualification = Qualification.new(qualification_params)
    if @qualification.save
      redirect_to user_qualifications_path
    else
      @qualifications = current_applicant.qualifications
      render :index
    end
  end

  def update
    @qualification = Qualification.find(params[:id])
    if @qualification.update(qualification_params)
      redirect_to user_qualifications_path
    else
      @qualifications = current_applicant.qualifications
      @qualification = Qualification.new
      render :index
    end
  end

  def destroy
    @qualification = Qualification.find(params[:id])
    @qualification.destroy
    redirect_to user_qualifications_path
  end
  
  private
  def qualification_params
    params.require(:qualification).permit(:applicant_id, :name, :acquition_date)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_furigana, :first_furigana,
                                                       :overview_w_history, :pg_skill, :self_pr, :vision,
                                                       :work_history_1, :work_history_2, :work_history_3,
                                                       :work_history_4, :work_history_5])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_top_path
  end

  def after_update_path_for(resource)
    user_top_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  skip_before_action :verify_signed_out_user

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    user_top_path
  end

  def after_sign_out_path_for(resource)
    new_applicant_session_path
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/user_notices_controller.rb
class User::UserNoticesController < ApplicationController
  def index
    @user_notices = current_applicant.user_notices
    @user_notices.where(is_check: false).each do |un|
      un.update_attributes(is_check: true)
    end
  end

  def destroy
    @user_notices =current_applicant.user_notices.destroy_all
    redirect_to user_user_notices_path
  end
end

app/helpers/corporations_helper.rb
module CorporationsHelper
end

app/views/user/corporations/show.html.erb
<body class="public-scene">
  <%= render partial: '/template/header' %>
  <%= render partial: '/template/nav' %>
  <main class="offerd">
    <div class="basic-info" style="height: auto;">
      <div class="title">
        <h2><%= @corporation.title %></h2>
        <h6><%= @corporation.name %> </h6>
      </div>
      <h4>タグ</h4>
      <table>
        <tr>
          <th>タグ</th>
          <td>
            <% @corporation.tags.each do |t| %>
              <span class="tag"><%= t.name %></span><br>
            <% end %>
          </td>
        </tr>
      </table>
      <h4>企業情報</h4>
      <table>
        <tr>
          <th>会社名</th>
          <td>
            <%= @corporation.name %>
          </td>
        </tr>
        <tr>
          <th>創業</th>
          <td><%= l @corporation.establish_day %></td>
        </tr>
        <tr>
          <th>従業員数</th>
          <td><%= @corporation.quantity_emp %></td>
        </tr>
      </table>
      <h4>募集要項</h4>
      <table>
        <tr>
          <th>仕事内容</th>
          <td>
            <%= safe_join(@corporation.business_description.split("\n"),tag(:br)) %>
          </td>
        </tr>
        <tr>
          <th>配属先情報</th>
          <td>
            <%= safe_join(@corporation.place_info.split("\n"),tag(:br)) %>
          </td>
        </tr>
        <tr>
          <th>必要な能力・経験</th>
          <td>
            <%= safe_join(@corporation.require_competence.split("\n"),tag(:br)) %>
          </td>
        </tr>
      </table>
      <h4>勤務条件</h4>
      <table>
        <tr>
          <th>雇用形態</th>
          <td>
            <% if @corporation.is_emp_status == true %>
              正社員
            <% else %>
              契約社員
            <% end %>
          </td>
        </tr>
        <tr>
          <th>年収</th>
          <td><%= @corporation.salary %>万円</td>
        </tr>
        <tr>
          <th>就業時間</th>
          <td><%= @corporation.working_hour %></td>
        </tr>
        <tr>
          <th>勤務地</th>
          <td><%= @corporation.work_location %></td>
        </tr>
        <tr>
          <th>通勤手当</th>
          <td><%= @corporation.commute_allowance %></td>
        </tr>
        <tr>
          <th>休日・休暇</th>
          <td><%= @corporation.day_off %></td>
        </tr>
      </table>
      <h4>制度・福利厚生</h4>
      <table>
        <tr>
          <th>健康保険</th>
          <td>
            <% if @corporation.is_health_insurance == true %>
              有
            <% else %>
              無
            <% end %>
          </td>
        </tr>
        <tr>
          <th>厚生年金</th>
          <td>
            <% if @corporation.is_welfare_pension == true %>
              有
            <% else %>
              無
            <% end %>
          </td>
        </tr>
        <tr>
          <th>雇用保険</th>
          <td>
            <% if @corporation.is_emp_insurance == true %>
              有
            <% else %>
              無
            <% end %>
          </td>
        </tr>
        <tr>
          <th>労災保険</th>
          <td>
            <% if @corporation.is_accident_insurance == true %>
              有
            <% else %>
              無
            <% end %>
          </td>
        </tr>
        <tr>
          <th>制度・福利厚生</th>
          <td>
            - 寮・社宅<br>
            <% if @corporation.is_dwelling == true %>
              有<br><br>
            <% else %>
              無<br><br>
            <% end %>
            - 退職金<br>
            <% if @corporation.is_retire_payment == true %>
              有<br><br>
            <% else %>
              無<br><br>
            <% end %>
            - その他制度<br>
            <%= safe_join(@corporation.other_welfare.split("\n"),tag(:br)) %>
          </td>
        </tr>
      </table>
      <h4>選考内容</h4>
      <table>
        <tr>
          <th>採用人数</th>
          <td><%= @corporation.recruit_number %>名</td>
        </tr>
        <tr>
          <th>面接回数</th>
          <td><%= @corporation.interview_number %>回</td>
        </tr>
      </table>
      <h4>企業情報</h4>
      <table>
        <tr>
          <th>企業名</th>
          <td><%= @corporation.name %></td>
        </tr>
        <tr>
          <th>代表取締役社長</th>
          <td><%= @corporation.president_name %></td>
        </tr>
        <tr>
          <th>設立</th>
          <td><%= l @corporation.establish_day %></td>
        </tr>
        <tr>
          <th>従業員数</th>
          <td><%= @corporation.quantity_emp %></td>
        </tr>
        <tr>
          <th>資本金</th>
          <td><%= @corporation.capital_stock %>百万円</td>
        </tr>
        <tr>
          <th>売上</th>
          <td>
            <% @corporation.sales.each do |sale| %>
              <table style="margin: 0;">
                <tr>
                  <th>年度</th>
                  <th>売上高</th>
                </tr>
                <tr>
                  <td style="width: 55%;"><%= sale.financial_year %></td>
                  <td><%= sale.year_sales %>百万円</td>
                </tr>
              </table>
            <% end %>
          </td>
        </tr>
        <tr>
          <th>所在地</th>
          <td>
            <%= @corporation.location %>
          </td>
        </tr>
        <tr>
          <th>企業URL</th>
          <td><%= @corporation.company_url %></td>
        </tr>
      </table>
    </div>
    <div class="decline">
      <% if current_applicant.already_room?(@corporation) %>
        <%= link_to 'メッセージ', room_path(@corporation), style: 'color: white; text-decoration: none;' %>
      <% elsif current_applicant.already_applied?(@corporation) %>
        <div>
          応募済
        </div>
      <% else %>
        <div>
          <%= link_to '応募する', user_corporation_applies_path(@corporation), method: :post %>
        </div>
      <% end %>
    </div>
  </main>
</body>