config/routes.rb
Rails.application.routes.draw do

  root 'user/homes#about'

  resources :rooms, only: [:show, :create, :index] do
    resources :messages, only: [:create]
  end
  
  
  devise_for :corporations, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  namespace :public do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'pg_search' => 'homes#pg_search', as: 'pg_search'
    get 'applicants/:id/work/' => 'applicants#work', as: 'work'
    get 'corporations/edit_job' => 'corporations#edit_job', as: 'edit_job_sheet'
    patch 'corporations/update_job' => 'corporations#update_job'
    get 'posts/applicant:id/specific_index' => 'posts#specific_index'
    get 'portfolios/applicant:id/specific_index' => 'portfolios#specific_index', as: 'specific_user'
    resource :corporations, only: [:show, :edit, :update]
    resources :applicants, only: [:index, :show] do
      resources :offers, only: [:create, :destroy]
    end
    resources :posts, only: [:index, :show]
    resources :portfolios, only: [:index, :show]
    resources :sales, except: [:show, :new, :edit]
    resources :applies, only: [:index]
    resources :corpo_notices, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :applicants, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
  }

  namespace :user do
    get 'top' => 'homes#top', as: 'top'
    get 'applicants/work' => 'applicants#work', as: 'work_history'
    get 'applicants/edit_work' => 'applicants#edit_work', as: 'edit_work_history'
    patch 'applicants/update_work' => 'applicants#update_work'
    resource :applicants, only: [:show, :edit, :update]
    resources :qualifications, except: [:show, :new, :edit]
    resources :posts, except: [:new]
    resources :portfolios
    resources :offers, only: [:index]
    resources :corporations, only: [:show] do
      resources :applies, only: [:create, :destroy]
    end
    resources :user_notices, only: [:index, :destroy]
  end
  
  
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  mount_uploader :image_id, ImageUploader

  has_many :qualifications, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :portfolios, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :offered_corporations, through: :offers, source: :corporation
  has_many :applies, dependent: :destroy
  has_many :applied_corporations, through: :applies, source: :corporation
  has_many :rooms, dependent: :destroy
  has_many :room_corporations, through: :rooms, source: :corporation
  has_many :user_notices, dependent: :destroy
  has_many :corpo_notices, dependent: :destroy
  has_many :tag_relations, dependent: :destroy
  has_many :tags, through: :tag_relations, dependent: :destroy
  has_many :pg_relations, dependent: :destroy
  has_many :pg_langs, through: :pg_relations, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_furigana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_furigana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true, uniqueness: true

  def already_applied?(corporation)
    self.applies.exists?(corporation_id: corporation.id)
  end

  def already_room?(corporation)
    self.rooms.exists?(corporation_id: corporation.id)
  end

  def full_name
    last_name + " " + first_name
  end

  def full_name_kana
    last_furigana + " " + first_furigana
  end

  def unchecked_user_notices
    self.user_notices.where(is_check: false)
  end

  def age
    date_format = "%Y%m%d"
    birthday = self.birth_date.to_date
    age = (Date.today.strftime(date_format).to_i - birthday.strftime(date_format).to_i) / 10000
  end
  

  enum gender:{
    "選択して下さい": 0,
    "男性": 1,
    "女性": 2
  }
  enum school_division:{
    "最終学歴を選んでください": 0,
    "中学": 1,
    "高校": 2,
    "高専": 3,
    "短大": 4,
    "大学": 5,
    "専門": 6
  }
  enum work_location:{
    "東京都":0,"東京23区":1,"北海道":2,"青森県":3,"岩手県":4,"宮城県":5,"秋田県":6,"山形県":7,"福島県":8,"茨城県":9,"栃木県":10,
    "群馬県":11,"埼玉県":12,"千葉県":13,"神奈川県":14,"新潟県":15,"富山県":16,"石川県":17,"福井県":18,"山梨県":19,"長野県":20,"岐阜県":21,"静岡県":22,"愛知県":23,
    "三重県":24,"滋賀県":25,"京都府":26,"大阪府":27,"兵庫県":28,"奈良県":29,"和歌山県":30,"鳥取県":31,"島根県":32,"岡山県":33,"広島県":34,"山口県":35,"徳島県":36,
    "香川県":37,"愛媛県":38,"高知県":39,"福岡県":40,"佐賀県":41,"長崎県":42,"熊本県":43,"大分県":44,"宮崎県":45,"鹿児島県":46,"沖縄県":47
  }
  enum axis:{
    "まだ決まっていない":0,
    "事業の成長性の高さ":1,
    "育児・介護休暇制度の活用実績":2,
    "学んできた言語を活かせる環境":3,
    "給与水準や昇給率の高さ":4,
    "住宅補助など給与以外の制度の充実":5,
    "堅実な事業":6,
    "フレックス制度の導入":7,
    "有給消化率の高さ":8,
    "残業時間の少なさ":9,
    "長期的に継続している事業":10,
    "２０代から責任ある仕事を任せる環境":11,
    "先鋭的な技術・サービス":12,
    "整った育成環境":13,
    "業界シェアの高さ":14,
    "既存業界に対する新しいアプローチ":15,
    "海外駐在の機会":16,
    "服装や働き方が自由な環境":17,
    "リモートワーク可能な環境":18
  }
  enum company_type:{
    "希望はない":0,
    "大手老舗":1,
    "中小老舗":2,
    "メガベンチャー":3,
    "ベンチャー":4
  }

  scope :search, -> (search_params) do
    return if search_params.blank?
    gender_is(search_params[:gender]).
    school_is(search_params[:school_division]).
    selection_is(search_params[:is_selection]).
    location_is(search_params[:work_location]).
    axis_is(search_params[:axis]).
    company_is(search_params[:company_type])
  end

  scope :gender_is, -> (gender) { where(gender: gender) if gender.present? }
  scope :school_is, -> (school_division) { where(school_division: school_division) if school_division.present? }
  scope :selection_is, -> (is_selection) { where(is_selection: is_selection) if is_selection.present? }
  scope :location_is, -> (work_location) { where(work_location: work_location) if work_location.present? }
  scope :axis_is, -> (axis) { where(axis: axis) if axis.present? }
  scope :company_is, -> (company_type) { where(company_type: company_type) if company_type.present? }

end

app/controllers/user/applicants_controller.rb
class User::ApplicantsController < ApplicationController
  before_action :authenticate_applicant!

  def show
    @qualifications = current_applicant.qualifications
  end

  def edit
    @applicant = current_applicant
  end

  def update
    @applicant = current_applicant
		if @applicant.update(applicant_params)
			redirect_to user_applicants_path
		else
			render action: :edit
    end
  end

  def work
  end

  def edit_work
    @applicant = current_applicant
  end

  def update_work
    @applicant = current_applicant
		if @applicant.update(applicant_params)
			redirect_to user_work_history_path
		else
			render action: :edit_work
    end
  end

  private
  def applicant_params
    params.require(:applicant).permit(:email, :last_name, :first_name, :last_furigana, :first_furigana, :gender, :birth_date, :image_id, :postal_code,
                                      :prefecture, :manicipal, :address_other, :phone_number, :school_division, :school_name, :faculty, :academic_decipline,
                                      :english_skill, :other_lang, :overview_w_history, :is_selection, :start_work, :work_location, :axis,
                                      :company_type, :pg_skill, :self_pr, :vision, :term_1, :term_2, :term_3, :term_4, :term_5, :work_history_1,
                                      :work_history_2, :work_history_3, :work_history_4, :work_history_5, :prefecture_kana, pg_lang_ids: [])
  end
end

app/controllers/user/applies_controller.rb
class User::AppliesController < ApplicationController
  before_action :authenticate_applicant!

  def create
    @apply = current_applicant.applies.create(corporation_id: params[:corporation_id])
    @apply.create_corpo_notice_apply(@apply.corporation.id, @apply.id, @apply.applicant.id)
    redirect_to user_corporation_path(@apply.corporation_id)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/corporations_controller.rb
class User::CorporationsController < ApplicationController
  before_action :authenticate_applicant!

  def show
    @corporation = Corporation.find(params[:id])
  end

  
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  def top
    @post = Post.new
    @offers = current_applicant.offers
    @rooms = current_applicant.rooms
    @applicant = current_applicant
  end

  def about
  end
  
end

app/controllers/user/offers_controller.rb
class User::OffersController < ApplicationController
  before_action :authenticate_applicant!

  def index
    @applicant = current_applicant
  end

end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/portfolios_controller.rb
class User::PortfoliosController < ApplicationController
  before_action :authenticate_applicant!

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      redirect_to user_portfolio_path(@portfolio)
    else
      render :new
    end
  end

  def show
    @portfolio = Portfolio.find(params[:id])
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    if @portfolio.update(portfolio_params)
      redirect_to user_portfolio_path(@portfolio)
    else
      render :show
    end
  end

  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy
    redirect_to user_portfolios_path
  end

  def index
    @portfolios = current_applicant.portfolios
  end
  
  private
  def portfolio_params
    params.require(:portfolio).permit(:applicant_id, :title, :content, :theme,
                                      :reason, :target, :scene, :link_url, pg_lang_ids: [])
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_applicant!

  def index
    @posts = current_applicant.posts
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to user_post_path(@post)
    else
      render 'homes/top'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_posts_path
    else
      render :show
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path
  end
  
  
  private
  def post_params
    params.require(:post).permit(:applicant_id, :pg_lang_id, :title, :content, pg_lang_ids: [])
  end
end

app/controllers/user/qualifications_controller.rb
class User::QualificationsController < ApplicationController
  before_action :authenticate_applicant!

  def index
    @qualifications = current_applicant.qualifications
    @qualification = Qualification.new
  end
  
  def create
    @qualification = Qualification.new(qualification_params)
    if @qualification.save
      redirect_to user_qualifications_path
    else
      @qualifications = current_applicant.qualifications
      render :index
    end
  end

  def update
    @qualification = Qualification.find(params[:id])
    if @qualification.update(qualification_params)
      redirect_to user_qualifications_path
    else
      @qualifications = current_applicant.qualifications
      @qualification = Qualification.new
      render :index
    end
  end

  def destroy
    @qualification = Qualification.find(params[:id])
    @qualification.destroy
    redirect_to user_qualifications_path
  end
  
  private
  def qualification_params
    params.require(:qualification).permit(:applicant_id, :name, :acquition_date)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_furigana, :first_furigana,
                                                       :overview_w_history, :pg_skill, :self_pr, :vision,
                                                       :work_history_1, :work_history_2, :work_history_3,
                                                       :work_history_4, :work_history_5])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_top_path
  end

  def after_update_path_for(resource)
    user_top_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  skip_before_action :verify_signed_out_user

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    user_top_path
  end

  def after_sign_out_path_for(resource)
    new_applicant_session_path
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/user_notices_controller.rb
class User::UserNoticesController < ApplicationController
  def index
    @user_notices = current_applicant.user_notices
    @user_notices.where(is_check: false).each do |un|
      un.update_attributes(is_check: true)
    end
  end

  def destroy
    @user_notices =current_applicant.user_notices.destroy_all
    redirect_to user_user_notices_path
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper

end

app/views/user/applicants/edit.html.erb
<body class="public-scene">
  <%= render partial: '/template/header' %>
  <%= render partial: '/template/nav', locals: { applicant: @applicant } %>
  <main class="user-info">
    <%= form_with model: @applicant, url: user_applicants_path(@applicant), method: :patch, local: true do |f| %>
      <div class="basic-info">
        <div>
          <%= image_tag current_applicant.image_id.url, class: "item_image" %><br>
          <%= f.file_field :image_id %>
        </div>
        <table>
          <tr>
            <td>ふりがな</td>
            <th><%= f.text_field :last_furigana %></th>
            <th><%= f.text_field :first_furigana %></th>
          </tr>
          <tr>
            <td>氏名</td>
            <th><%= f.text_field :last_name %></th>
            <th><%= f.text_field :first_name %></th>
          </tr>
          <tr>
            <td>生年月日</td>
            <th><%= f.date_select :birth_date, use_month_numbers: true, start_year: 1960, end_year: (Time.now.year - 10) %></th>
          </tr>
          <tr>
            <td>性別</td>
            <th><%= f.select :gender, Applicant.genders.keys.to_a, include_blank: false %></th>
          </tr>
          <tr>
            <td>郵便番号</td>
            <th>
              <%= f.label :postal_code, "(ハイフンなし)", style: 'font-size: 10px;' %><br>
              <%= f.text_field :postal_code %>
            </th>
          </tr>
          <tr>
            <td>ふりがな</td>
            <th><%= f.text_field :prefecture_kana %></th>
          </tr>
          <tr>
            <td>住所</td>
            <th>
              都道府県　<%= f.text_field :prefecture %><br>
              市町村区　<%= f.text_field :manicipal %><br>
              その他　　<%= f.text_field :address_other %>
            </th>
          </tr>
          <tr>
            <td>TEL</td>
            <th><%= f.text_field :phone_number %></th>
          </tr>
          <tr>
            <td>email</td>
            <th><%= f.text_field :email %></th>
          </tr>
        </table>
      </div>
    <div class="ability">
      <h4>学習言語</h4>
      <table>
        <tr>
          <td>
            <%= f.collection_check_boxes(:pg_lang_ids, PgLang.all, :id, :name) do |tag| %>
              <%= tag.label do %>
                <%= tag.check_box %>
                <%= tag.text %>
              <% end %>
            <% end %>
          </td>
        </tr>
      </table>
      <h4>プログラミングスキル</h4>
      <%= f.text_area :pg_skill, placeholder: "2020年4月~1ヶ月間,progateで独学をした後、（HTML/CSS, JavaScript, jQuery, Ruby, Ruby on Rails, Sass)2020年５月からDMM WEBCAMP専門技術講座を受講 (HTML/CSS, Ruby, Ruby on Rails, JavaScript, Git, AWS)" %>
    </div>
    <div class="pr">
      <h4>プロフィール（PR）</h4>
      <h6>自己PR</h6>
        <%= f.text_area :self_pr %>
      <h6>私の将来像</h6>
        <%= f.text_area :vision %>
    </div>
    <div class="qualification">
      <h4>語学</h4>
      <ul>
        <li>
          <p>英語</p>
          <%= f.text_field :english_skill, placeholder: '例）2017年4月　TOEIC公開テスト　スコア600点取得' %>
        </li>
        <li>
          <p>その他語学</p>
          <%= f.text_field :other_lang, placeholder: '中国語など' %>
        </li>
      </ul>
    </div>
    <div class="desire">
      <h4>希望する企業タイプ</h4>
      <%= f.select :company_type, Applicant.company_types.keys.to_a, include_blank: false %>
      <h4>希望勤務地</h4>
      <%= f.select :work_location, Applicant.work_locations.keys.to_a, include_blank: false %>
      <h4>勤務開始可能日</h4>
      <%= f.text_field :start_work, placeholder: '例）20XX年○月○日以降になります' %>
    </div>
    <div class="item-6">
      <h4>転職の軸</h4>
      <%= f.select :axis, Applicant.axes.keys.to_a, include_blank: false %>
    </div>
    <div class="item-7">
      <h4>転職活動状況</h4>
      <div class="selection">
        <%= f.radio_button :is_selection, :true %>
        <%= f.label :is_selection, "転職活動中" %>  
        <%= f.radio_button :is_selection, :false %>
        <%= f.label :is_selection, "活動終了" %>
      </div>
    </div>
    <div class="e-submit">
      <%= f.submit '保存', class: 'submit' %>
    </div>
    <% end %>
  </main>
</body>

app/views/user/applicants/edit_work.html.erb
<body class="public-scene", style="height:1900px;">
  <%= render partial: '/template/header' %>
  <%= render partial: '/template/nav' %>
  <main class="user-info">
    <%= form_with model: @applicant, url: user_applicants_update_work_path(@applicant), method: :patch, local: true do |f| %>
      <%= render partial: '/template/user_info' %>
      <div class="ability">
        <h4>学歴</h4>
        <table>
          <tr>
            <td>学校区分</td>
            <th>
              <%= f.select :school_division, Applicant.school_divisions.keys.to_a, include_blank: false %>
            </th>
          </tr>
          <tr>
            <td>学校名</td>
            <th>
              <%= f.text_field :school_name, class: 'form' %>
            </th>
          </tr>
          <tr>
            <td>学部</td>
            <th>
              <%= f.text_field :faculty, class: 'form' %>
            </th>
          </tr>
          <tr>
            <td>学科</td>
            <th>
              <%= f.text_field :academic_decipline, class: 'form' %>
            </th>
          </tr>
        </table>
      </div>
      <div class="pr">
        <h4>職務経歴</h4>
        <h6>職歴要約</h6>
        <%= f.text_area :overview_w_history, class: 'text-box' %>
        <h6>職務経歴</h6>
        <table border="1" style="border-collapse: collapse">
          <tr>
            <th class="period">期間</th>
            <th>職務内容</th>
          </tr>
          <tr>
            <td>
              <%= f.text_field :term_1 %>
            </td>
            <td>
              <%= f.text_area :work_history_1 %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.text_field :term_2 %>
            </td>
            <td>
              <%= f.text_area :work_history_2 %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.text_field :term_3 %>
            </td>
            <td>
              <%= f.text_area :work_history_3 %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.text_field :term_4 %>
            </td>
            <td>
              <%= f.text_area :work_history_4 %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.text_field :term_5 %>
            </td>
            <td>
              <%= f.text_area :work_history_5 %>
            </td>
          </tr>
        </table>
      </div>
      <div>
        <%= f.submit "保存する", class: 'save' %>
      </div>
    <% end %>
  </main>
</body>

app/views/user/applicants/show.html.erb
<body class="public-scene">
  <%= render partial: '/template/header' %>
  <%= render partial: '/template/nav' %>
  <main class="user-info">
    <%= render partial: '/template/user_info' %>
    <div class="ability">
      <h4>学習言語</h4>
      <table>
        <tr>
          <td>
            <% current_applicant.pg_langs.each do |pg| %>
              <%= pg.name %>,
            <% end %>      
          </td>
        </tr>
      </table>
      <h4>プログラミングスキル</h4>
      <div style="margin: 30px 50px; font-size: 20px;">
        <span class="tag"><%= simple_format(current_applicant.pg_skill) %></span>
      </div>
    </div>
    <div class="pr">
      <h4>プロフィール（PR）</h4>
      <h6>自己PR</h6>
      <div style="margin: 30px 50px; font-size: 20px;">
        <%= simple_format(current_applicant.self_pr) %>
      </div>
      <h6>私の将来像</h6>
      <div style="margin: 30px 50px; font-size: 20px;">
        <%= simple_format(current_applicant.vision) %>
      </div>
    </div>
    <div class="qualification">
      <h4>語学・資格</h4>
      <div class="quali-box">
          <ul>
            <li>
              <p>英語</p>
              <%= current_applicant.english_skill %>
            </li>
            <li>
              <p>その他語学</p>
              <%= current_applicant.other_lang %>
            </li>
          </ul>
          <ul>
            <li>
              <p>資格</p>
              <% current_applicant.qualifications.each do |q| %>
                <%= q.name %><br>
              <% end %>
            </li>
          </ul>
      </div>
    </div>
    <div class="desire">
      <h4>希望する企業タイプ</h4>
      <div class="desire-box">
        <%= current_applicant.company_type %>
      </div>
      <h4>転職の軸</h4>
      <div class="desire-box">
        <%= current_applicant.axis %>
      </div>
      <h4>希望勤務地</h4>
      <div class="desire-box">
        <%= current_applicant.work_location %>
      </div>
      <h4>勤務開始可能日</h4>
      <div class="desire-box">
        <%= current_applicant.start_work %>
      </div>
    </div>
    <div class="item-6">
      
    </div>
    <div class="item-7">
      <h4>転職活動状況</h4>
      <div class="desire-box">
        <% if current_applicant.is_selection == true  %>
          <span class="text-active">転職活動中</span>
        <% else %>
          <span class="text-invalid">活動終了</span>							
        <% end %>
      </div>
    </div>
    <div class="submit">
      <%= link_to '編集', edit_user_applicants_path, class: 'submit', style: 'text-decoration: none;' %>
    </div>
  </main>
</body>

app/views/user/applicants/work.html.erb
<body class="public-scene">
  <%= render partial: '/template/header' %>
  <%= render partial: '/template/nav' %>
  <main class="user-info">
    <%= render partial: '/template/user_info' %>
    <div class="ability">
      <h4>学歴</h4>
      <table>
        <tr>
          <td>学校区分</td>
          <th><%= current_applicant.school_division %></th>
        </tr>
        <tr>
          <td>学校名</td>
          <th><%= current_applicant.school_name %></th>
        </tr>
        <tr>
          <td>学部</td>
          <th><%= current_applicant.faculty %></th>
        </tr>
        <tr>
          <td>学科</td>
          <th><%= current_applicant.academic_decipline %></th>
        </tr>
      </table>
    </div>
    <div class="pr">
      <h4>職務経歴</h4>
      <h6>職歴要約</h6>
      <div class="text-box">
        <%= simple_format(current_applicant.overview_w_history) %>
      </div>
      <h6>職務経歴</h6>
      <table border="1" style="border-collapse: collapse">
        <tr>
          <th class="period">期間</th>
          <th>職務内容</th>
        </tr>
        <tr>
          <td><%= simple_format(current_applicant.term_1) %></td>
          <td><%= simple_format(current_applicant.work_history_1) %></td>
        </tr>
        <tr>
          <td><%= simple_format(current_applicant.term_2) %></td>
          <td><%= simple_format(current_applicant.work_history_2) %></td>
        </tr>
        <tr>
          <td><%= simple_format(current_applicant.term_3) %></td>
          <td><%= simple_format(current_applicant.work_history_3) %></td>
        </tr>
        <tr>
          <td><%= simple_format(current_applicant.term_4) %></td>
          <td><%= simple_format(current_applicant.work_history_4) %></td>
        </tr>
        <tr>
          <td><%= simple_format(current_applicant.term_5) %></td>
          <td><%= simple_format(current_applicant.work_history_5) %></td>
        </tr>
      </table>
    </div>
    <div class="submit">
      <%= link_to '編集', user_edit_work_history_path, class: 'submit', style: 'text-decoration: none;' %>
    </div>
  </main>
</body>