config/routes.rb
Rails.application.routes.draw do

  root 'user/homes#about'

  resources :rooms, only: [:show, :create, :index] do
    resources :messages, only: [:create]
  end
  
  
  devise_for :corporations, controllers: {
    sessions: 'public/sessions',
    registrations: 'public/registrations',
  }

  namespace :public do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'pg_search' => 'homes#pg_search', as: 'pg_search'
    get 'applicants/:id/work/' => 'applicants#work', as: 'work'
    get 'corporations/edit_job' => 'corporations#edit_job', as: 'edit_job_sheet'
    patch 'corporations/update_job' => 'corporations#update_job'
    get 'posts/applicant:id/specific_index' => 'posts#specific_index'
    get 'portfolios/applicant:id/specific_index' => 'portfolios#specific_index', as: 'specific_user'
    resource :corporations, only: [:show, :edit, :update]
    resources :applicants, only: [:index, :show] do
      resources :offers, only: [:create, :destroy]
    end
    resources :posts, only: [:index, :show]
    resources :portfolios, only: [:index, :show]
    resources :sales, except: [:show, :new, :edit]
    resources :applies, only: [:index]
    resources :corpo_notices, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :applicants, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations',
  }

  namespace :user do
    get 'top' => 'homes#top', as: 'top'
    get 'applicants/work' => 'applicants#work', as: 'work_history'
    get 'applicants/edit_work' => 'applicants#edit_work', as: 'edit_work_history'
    patch 'applicants/update_work' => 'applicants#update_work'
    resource :applicants, only: [:show, :edit, :update]
    resources :qualifications, except: [:show, :new, :edit]
    resources :posts, except: [:new]
    resources :portfolios
    resources :offers, only: [:index]
    resources :corporations, only: [:show] do
      resources :applies, only: [:create, :destroy]
    end
    resources :user_notices, only: [:index, :destroy]
  end
  
  
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :pg_relations, dependent: :destroy
  has_many :pg_langs, through: :pg_relations, dependent: :destroy
  belongs_to :applicant

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/user/applicants_controller.rb
class User::ApplicantsController < ApplicationController
  before_action :authenticate_applicant!

  def show
    @qualifications = current_applicant.qualifications
  end

  def edit
    @applicant = current_applicant
  end

  def update
    @applicant = current_applicant
		if @applicant.update(applicant_params)
			redirect_to user_applicants_path
		else
			render action: :edit
    end
  end

  def work
  end

  def edit_work
    @applicant = current_applicant
  end

  def update_work
    @applicant = current_applicant
		if @applicant.update(applicant_params)
			redirect_to user_work_history_path
		else
			render action: :edit_work
    end
  end

  private
  def applicant_params
    params.require(:applicant).permit(:email, :last_name, :first_name, :last_furigana, :first_furigana, :gender, :birth_date, :image_id, :postal_code,
                                      :prefecture, :manicipal, :address_other, :phone_number, :school_division, :school_name, :faculty, :academic_decipline,
                                      :english_skill, :other_lang, :overview_w_history, :is_selection, :start_work, :work_location, :axis,
                                      :company_type, :pg_skill, :self_pr, :vision, :term_1, :term_2, :term_3, :term_4, :term_5, :work_history_1,
                                      :work_history_2, :work_history_3, :work_history_4, :work_history_5, :prefecture_kana, pg_lang_ids: [])
  end
end

app/controllers/user/applies_controller.rb
class User::AppliesController < ApplicationController
  before_action :authenticate_applicant!

  def create
    @apply = current_applicant.applies.create(corporation_id: params[:corporation_id])
    @apply.create_corpo_notice_apply(@apply.corporation.id, @apply.id, @apply.applicant.id)
    redirect_to user_corporation_path(@apply.corporation_id)
  end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/corporations_controller.rb
class User::CorporationsController < ApplicationController
  before_action :authenticate_applicant!

  def show
    @corporation = Corporation.find(params[:id])
  end

  
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  def top
    @post = Post.new
    @offers = current_applicant.offers
    @rooms = current_applicant.rooms
    @applicant = current_applicant
  end

  def about
  end
  
end

app/controllers/user/offers_controller.rb
class User::OffersController < ApplicationController
  before_action :authenticate_applicant!

  def index
    @applicant = current_applicant
  end

end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/portfolios_controller.rb
class User::PortfoliosController < ApplicationController
  before_action :authenticate_applicant!

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)
    if @portfolio.save
      redirect_to user_portfolio_path(@portfolio)
    else
      render :new
    end
  end

  def show
    @portfolio = Portfolio.find(params[:id])
  end

  def update
    @portfolio = Portfolio.find(params[:id])
    if @portfolio.update(portfolio_params)
      redirect_to user_portfolio_path(@portfolio)
    else
      render :show
    end
  end

  def destroy
    @portfolio = Portfolio.find(params[:id])
    @portfolio.destroy
    redirect_to user_portfolios_path
  end

  def index
    @portfolios = current_applicant.portfolios
  end
  
  private
  def portfolio_params
    params.require(:portfolio).permit(:applicant_id, :title, :content, :theme,
                                      :reason, :target, :scene, :link_url, pg_lang_ids: [])
  end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_applicant!

  def index
    @posts = current_applicant.posts
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to user_post_path(@post)
    else
      render 'homes/top'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_posts_path
    else
      render :show
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path
  end
  
  
  private
  def post_params
    params.require(:post).permit(:applicant_id, :pg_lang_id, :title, :content, pg_lang_ids: [])
  end
end

app/controllers/user/qualifications_controller.rb
class User::QualificationsController < ApplicationController
  before_action :authenticate_applicant!

  def index
    @qualifications = current_applicant.qualifications
    @qualification = Qualification.new
  end
  
  def create
    @qualification = Qualification.new(qualification_params)
    if @qualification.save
      redirect_to user_qualifications_path
    else
      @qualifications = current_applicant.qualifications
      render :index
    end
  end

  def update
    @qualification = Qualification.find(params[:id])
    if @qualification.update(qualification_params)
      redirect_to user_qualifications_path
    else
      @qualifications = current_applicant.qualifications
      @qualification = Qualification.new
      render :index
    end
  end

  def destroy
    @qualification = Qualification.find(params[:id])
    @qualification.destroy
    redirect_to user_qualifications_path
  end
  
  private
  def qualification_params
    params.require(:qualification).permit(:applicant_id, :name, :acquition_date)
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_furigana, :first_furigana,
                                                       :overview_w_history, :pg_skill, :self_pr, :vision,
                                                       :work_history_1, :work_history_2, :work_history_3,
                                                       :work_history_4, :work_history_5])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_top_path
  end

  def after_update_path_for(resource)
    user_top_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  skip_before_action :verify_signed_out_user

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    user_top_path
  end

  def after_sign_out_path_for(resource)
    new_applicant_session_path
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/user_notices_controller.rb
class User::UserNoticesController < ApplicationController
  def index
    @user_notices = current_applicant.user_notices
    @user_notices.where(is_check: false).each do |un|
      un.update_attributes(is_check: true)
    end
  end

  def destroy
    @user_notices =current_applicant.user_notices.destroy_all
    redirect_to user_user_notices_path
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/user/homes/about.html.erb
<body class="about">
  <header>
    <h3></h3>
    <div class="user-log">
      <p>
        <%= link_to '新規登録', new_applicant_registration_path, style: 'color: white;' %>
      </p>
    </div>
    <div class="corpo-log">
      <p>
        <%= link_to 'ログイン', new_applicant_session_path, style: 'color: white;' %>
      </p>
    </div>
  </header>
  <main>
    <h3>【初めての方へ】Grow IT Talentってどんなサービス？</h3>
    <h4 class="sub-ttl">従来の転職と真逆！企業からあなたに直接声がかかる仕組み！</h4>
    <div class="conventional">
      <h5>従来のエントリー型</h5>
      <p>お互いのことをよく知らないまま、主に求職者から応募。応募が殺到した場合は面接の機会も得られないことも。</p>
    </div>
    <div class="gitt">
      <h5>Grow IT Talentのオファー型</h5>
      <p>企業からあなたに直接声がかかる、オファー型。１対１のコミュニケーションを通じて、相互理解を深められます。</p>
    </div>
    <h2 class="cap">Grow IT Talentの特徴</h2>
    <div class="feature">
      <p>あなたの学習経過を企業にアピール</p>
      <p>「ポテンシャル」で勝負できる！</p>
      <p class="detail">Grow IT Talentは履歴書・職務経歴書を入力するだけでなく、これまでの学習経過や現在学習中の言語、ポートフォリオをプロフィールに投稿することができます。<br>
          これまでの学習中の意識・工夫、今後身につけたいスキルなどを投稿してあなたの「ポテンシャル」を企業にアピールしましょう。</p>
    </div>
    <h2 class="flow">登録から選考までの流れ</h2>
    <div class="card-1">
      <p>プロフィール作成</p>
      <p class="detail">今の自分を振り返り、プログラミングスキルをまとめます。今までどんな言語を学んできたのか、興味のあることは何か。Grow IT Talentでは過去、現在、未来のあなたを表現できます。</p>
    </div>
    <div class="card-2">
      <p>オファーを獲得！</p>
      <p class="detail">プロフィールを磨いて、企業からオファーをもらおう！</p>
    </div>
    <div class="card-3">
      <p>選考がスタート！</p>
      <p class="detail">Grow IT Talentでは、人物をよくみて「相互理解」を深める少人数制の選考を推奨しており、ミスマッチ解決に取り組んでいます。オファーから始まり、1対1のコミュニケーションを重ね、企業との距離を縮めていくことができます。</p>
    </div>
    <div class="regest">
      <%= link_to '新規登録', new_applicant_registration_path, style: 'color: white;' %>
    </div>
  </main>
</body>

app/views/user/homes/top.html.erb
<body class="public-scene">
  <%= render partial: '/template/header' %>
  <%= render partial: '/template/nav' %>
  <main class="user-top">
    <div class="job-offer">
      <h4>企業オファー</h4>
      <% if @offers.any? %>
        <% @applicant.offered_corporations.order(updated_at: :desc).limit(5).each do |c| %>
          <table>
            <tr>
              <td class="qual-form" style="width: 20%;">
                <%= l c.created_at, format: :short %>
              </td>
              <td class="qual-form">
                <%= c.name %>
              </td>
              <td class="qual-form" style="width: 16%;">
                <%= link_to '詳しく見る', user_corporation_path(c), style: 'font-size: 12px;' %>
              </td>
            </tr>
          </table>
        <% end %>
      <% end %>
    </div>
    <div class="schedule">
      <h4>メッセージ一覧</h4>
      <% @applicant.rooms.order(updated_at: :desc).limit(5).each do |r| %>
        <table>
          <tr>
            <td class="qual-form">
              <%= r.corporation.name %>
            </td>
            <td class="qual-form" style="width: 16%;">
              <%= link_to '詳しく見る', room_path(r), style: 'font-size: 12px;' %>
            </td>
          </tr>
        </table>
      <% end %>
    </div>
    <div class="study-post">
      <h4>学習記事投稿</h4>
      <%= form_with model: @post, url: user_posts_path, method: :post, style: 'height: 400px;' do |f| %>
        <%= f.label :title, 'タイトル' %><br>
        <%= f.text_field :title %><br>
        <%= f.hidden_field :applicant_id, :value => current_applicant.id %>
        <table>
          <tr>
            <td>
              <%= f.collection_check_boxes(:pg_lang_ids, PgLang.all, :id, :name) do |tag| %>
                <%= tag.label do %>
                  <%= tag.check_box %>
                  <%= tag.text %>
                <% end %>
              <% end %>
            </td>
          </tr>
        </table>
        <br>
        <%= f.text_area :content, :placeholder =>"ここに記事内容を書いてください" %><br>
        <%= f.submit "投稿", style: 'border-radius: 7px; width: 15%;' %>
      <% end %>
    </div>
  </main>
</body>
</html>